name: exercise_one_test

on: [push]

jobs:
  question-two:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question Two
        run: |
          cd Exercise1
          make questionTwo
      
      - name: Test question Two
        run: |
          cd Exercise1
          build/questionTwo
  
  question-three:
    runs-on: ubuntu-latest
    needs: question-two
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question Three
        run: |
          cd Exercise1
          make questionThree

      - name: Test question Three
        run: |
          cd Exercise1
          build/questionThree
  
  question-four:
    runs-on: ubuntu-latest
    needs: question-three
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question Four
        run: |
          cd Exercise1
          make questionFour

      - name: Test question Four
        run: |
          cd Exercise1
          build/questionFour

  question-five:
    runs-on: ubuntu-latest
    needs: question-four
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question Five
        run: |
          cd Exercise1
          make questionFive

      - name: Test question Five
        run: |
          cd Exercise1
          build/questionFive

  question-six:
    runs-on: ubuntu-latest
    needs: question-five
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question Six
        run: |
          cd Exercise1
          make questionSix

      - name: Test question Six
        run: |
          cd Exercise1
          build/questionSix

  question-seven:
    runs-on: ubuntu-latest
    needs: question-six
    steps:
      - name: Check repository
        uses: actions/checkout@v3
        
      - name: Build test exec for question Seven
        run: |
          cd Exercise1
          make questionSeven

      - name: Test question Seven
        run: |
          cd Exercise1
          build/questionSeven

      
