name: exercise_one_test

on: [push]

jobs:
  question-two:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build test exec for question two
        run: |
          cd Exercise1
          make questionTwo
      
      - name: Test question one
        run: ./build/questionTwo

      
