name: exercise_two_test

on: [push]

jobs:
  check-helloworld-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "Exercise2/srcs/helloworld.c"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo All files exists!
      
      - name: File don't exit
        if: steps.check_files.outputs.files_exists == 'false'
        run: exit 1
  
  sub-exercise-one:
    runs-on: ubuntu-latest
    needs: check-helloworld-file
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build helloworld exec
        run: |
          cd Exercise2
          make questionOneOne
      
      - name: Tests helloworld exec
        run: |
          cd Exercise2/tests
          go run main.go -questions